var B=!1,C=/^bytes [0-9]+-[0-9]+\/([0-9]+)$/,aa=/:\/\/.+\/([^/]+?(?:.([^./]+?))?)(?=[?#]|$)/,ba=[301,302,303,307,308],G="object xmlhttprequest media other main_frame sub_frame image".split(" "),ca="7Z ARJ BIN BZ2 EXE DLL IMG ISO LZH MSI MSU PLJ PPS PPT RA RAR SEA SIT SITX TAR TIF TIFF Z ZIP ZIPX TAR GZ XZ BZ CAB ARC PAK APK NRG NRI OMG IMG SFX DMG DMGPART XIP TGZ ZZ TXZ PKG HQX GZIP DOC DOCX XLS XLSX PPTX ODT ODS WPD TEX RTF RTFD EPUB KEY NUMBERS PAGES".split(" "),H=/^(?:FLV|SWF|MP3|MP4|M4V|F4F|F4V|M4A|MPG|MPEG|MPEG4|MPE|AVI|WMV|WMA|WAV|WAVE|ASF|RM|RAM|OGG|OGV|OGM|OGA|MOV|MID|MIDI|3GP|3GPP|QT|WEBM|TS|MKV|AAC|MP2T|MPEGTS|TS|RMVB)$/i,
da=/^(?:F4F|MPEGTS|TS|MP2T)$/i,I={"application/x-apple-diskimage":"DMG","application/epub+zip":"EPUB","application/java-archive":"JAR","video/x-matroska":"MKV","text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|SRT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|F4M|TTML","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON",
"application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-gtar":"TAR","application/x-msi":"MSI","application/x-msp":"MSP","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8",
"application/x-msdos-program":"EXE|DLL","application/vnd.apple.installer+xml":"MPKG","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M",
"video/flv":"FLV","video/mp2t":"TS|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG|MPE","video/mpegurl":"M3U8|M3U","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U8|M3U","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4",
"audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U8|M3U","image/svg+xml":"SVG|SVGZ","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U8|M3U","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV",
"image/x-xbitmap":"XBM","audio/x-mp3":"MP3","audio/x-hx-aac-adts":"AAC","audio/aac":"AAC","audio/x-aac":"AAC","application/vnd.rn-realmedia-vbr":"RMVB"};function J(a){return a&&unescape(a.split(";",1).shift().trim())||""}function K(a){return(a=aa.exec(a))?a[1]||"":""}function L(a){return-1<a.indexOf(".")?a.split(".").pop():""}function ea(a){var b;a=a.toUpperCase();for(b in I)if(-1<I[b].split("|").indexOf(a))return b;return""}
function M(a,b){if(!a)return null;for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b.toLowerCase())return a[c].value||a[c].binaryValue||null;return null}function N(){for(var a={},b=0;b<arguments.length;b++)for(var c in arguments[b])arguments[b].hasOwnProperty(c)&&(a[c]=arguments[b][c]);return a}function O(a,b){return a&&b&&0==a.indexOf(b)}function P(a,b){if(!a||!b)return!1;var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function Q(a,b){return a&&b&&0<=a.indexOf(b)}
function R(a){return Q(a,"://")?a.split("://",1).shift().toLowerCase()||"":"http"}function fa(a){var b="";a&&(a=a.trim());a&&(b=(new URL(a)).origin);return b}
function S(a,b){var c=b&&b["1"]||"GET",e=new XMLHttpRequest,d;e.open(c,a["2"],!0);e.onreadystatechange=function(){4==e.readyState&&(a.G||function(){})(e.responseText)};e.timeout=15E3;if(b&&(d=b.l))for(var f=0;f<d.length;f++)O(d[f].name.toLowerCase(),"x-")&&e.setRequestHeader(d[f].name,d[f].value);if("POST"==c&&b)try{T(b,b),b["10"]&&e.setRequestHeader("Content-Type",b["10"]),b["11"]&&e.setRequestHeader("Content-Disposition",b["11"])}catch(g){}c=null;b&&b.postData&&(c=b.postData);e.send(c)}
function U(){this["1"]="GET";this["2"]="";this["3"]="";this["4"]="";this["5"]="";this["6"]="normal";this["7"]=0;this["8"]="";this["9"]="";this["10"]="";this.cookies=this["11"]="";this.postData=null}
function V(){var a=this.constructor.prototype,b;for(b in a)this[b]=a[b].bind(this);this.H={};this.g={};this.j={};this.aa=1;this.v=!1;chrome.contextMenus.create({title:"Download by NeatDownloadManager",contexts:["link","image"],onclick:this.T});this.m(chrome.runtime.onConnect,this.U);this.m(chrome.webRequest.onBeforeRequest,this.N,{urls:["http://*/*","https://*/*","ftp://*/*"],types:G},["requestBody"]);this.m(chrome.webRequest.onBeforeSendHeaders,this.O,{urls:["https://*/*","http://*/*"],types:G},
["requestHeaders"]);this.m(chrome.webRequest.onHeadersReceived,this.R,{urls:["<all_urls>"],types:G},["responseHeaders"]);this.m(chrome.webRequest.onResponseStarted,this.C,{urls:["<all_urls>"]});this.m(chrome.webRequest.onCompleted,this.C,{urls:["<all_urls>"]});this.m(chrome.webRequest.onErrorOccurred,this.C,{urls:["<all_urls>"]});chrome.browserAction.onClicked.addListener(this.S);this.h=this.B=null;this.A=!1;this.K()}var W=V.prototype;W.S=function(a){this.ba(a.id)};
W.I=function(a){var b=this;if(this.A){var c="1:"+a["1"]+"\r\n";c+="2:"+a["2"]+"\r\n";a["3"]&&(c+="3:"+a["3"]+"\r\n");c+="6:"+(a["6"]||"normal")+"\r\n";a["4"]&&(c+="4:"+a["4"]+"\r\n");a.pageUrl&&(c+="Origin: "+fa(a.pageUrl)+"\r\n");a.pageUrl&&(c+="Referer: "+a.pageUrl+"\r\n");a["5"]&&(c+="5:"+a["5"]+"\r\n");a.cookies&&(c+="Cookie: "+a.cookies+"\r\n");a["10"]&&(c+="Content-Type: "+a["10"]+"\r\n");a["11"]&&(c+="Content-Disposition: "+a["11"]+"\r\n");a["9"]&&(c+="9:"+a["9"]+"\r\n");for(var e in a)O(e.toLowerCase(),
"x-")&&(c+=e+": "+a[e]+"\r\n");"POST"==a["1"]&&(a["7"]&&(c+="7:"+a["7"]+"\r\n"),a["8"]&&(c+="8:"+a["8"]+"\r\n"),c=a.postData?c+("__0NeatPostData9__:"+a.postData):c+"Content-Length: 0\r\n");if(!(102400<c.length))if(a["3"])this.B.send(c),this.h=null;else if("POST"==a["1"]||!this.v||a["7"]&&a["8"])"POST"!=a["1"]&&this.v&&(c+="8:"+a["8"]+"\r\n",c+="7:"+a["7"]+"\r\n"),this.B.send(c),this.h=null;else{var d=new XMLHttpRequest;d.open("HEAD",a["2"],!0);d.onreadystatechange=function(){4==d.readyState&&(a["8"]=
a["8"]||d.getResponseHeader("Content-Type")||"",a["7"]=a["7"]||d.getResponseHeader("Content-Length")||0,c+="8:"+a["8"]+"\r\n",c+="7:"+a["7"]+"\r\n",b.B.send(c),b.h=null)};d.timeout=8E3;d.send()}}else this.h=a,this.K()};W.K=function(){var a=new WebSocket(atob("d3M6Ly8xMjcuMC4wLjE6MTAwMDcvZG93bmxvYWQ="),atob("bmVhdGV4dGVuc2lvbi52MQ=="));a.onopen=this.$;a.onclose=this.X;a.onmessage=this.Z;a.onerror=this.Y;this.B=a};W.$=function(){this.A=!0;this.h&&this.I(this.h)};W.X=function(){this.A=!1;this.h=null};
W.Z=function(a){a=a.data;"waiting"==a?this.v=!0:"nowaiting"==a&&(this.v=!1)};W.Y=function(){this.A=!1;this.h&&alert("Extension Can't Connect to NeatDownloadManager Application.You Can : \r\n1- Check If NeatDownloadManager is Running.\r\n2- or Hold down Delete-Key and click on your Download link.\r\n3- or Disable NeatDownloadManager Extension temporarily.");this.h=null};
W.J=function(a){if(this.h){var b="";if(a&&0<a.length)for(var c=0;c<a.length;c++)b+=a[c].name+"="+a[c].value+(c<a.length-1?"; ":"");b=b.trim();this.h.cookies=b;this.I(this.h)}};W.T=function(a,b){var c=R(a.linkUrl);!c||"ftp"!=c&&"http"!=c&&"https"!=c||"ftp"==c&&!K(a.linkUrl)||(c=new U,c["2"]=a.linkUrl||a.srcUrl,c.pageUrl=a.pageUrl,c["4"]=b&&b.title||"",b&&b.url&&(c["5"]=b.url),!c["5"]&&(c["5"]=a.pageUrl),this.h=c,chrome.cookies.getAll({url:c["2"]},this.J))};
function X(a,b){this.g=a;this.h=b||"m3u8"}
function ha(a,b,c){var e=[],d=0,f="";if("json"==a.h)try{var g=0==b["2"].indexOf("https"),n=JSON.parse(c);n.hls_url&&!g&&e.push({2:n.hls_url,tags:{}});n.https_hls_url&&g&&e.push({2:n.https_hls_url,tags:{}})}catch(l){}if("m3u8"==a.h){c=c.split(/[\r\n]+/);if(0==c.length||"#EXTM3U"!=c[0].trim())return;for(var u=n=g=!1,z="",D=/^#(EXT[^\s:]+)(?::(.*))/,A=1;A<c.length;A++){var h=c[A].trim();h&&("#"==h[0]?0==h.indexOf("#EXT")&&(h=D.exec(h))&&(g||(g="EXTINF"==h[1])&&(z=h[2]),n||(n="EXT-X-STREAM-INF"==h[1])&&
(z=h[2]),u||(u="EXT-X-BYTERANGE"==h[1])):(g&&(d+=parseFloat(z),g=!1),n&&(e.push({2:(new URL(h,b["2"])).href,tags:z}),n=!1),u&&!f&&(f=(new URL(h,b["2"])).href)))}}if(f){c="";d&&(60<d&&(c+=parseInt(d/60)+" min "),c+=parseInt(d%60)&&parseInt(d%60)+" sec");var p={6:"media",fEx:"ts",4:"TS File "+c,fDu:c};p=N(p,{1:b["1"],2:f,tabId:b.tabId,frameId:b.frameId,fS:b["7"],fileName:b.fileName});Y(b,p);"POST"==p["1"]&&T(b,p);setTimeout(function(){a.g.o(p)},3E3)}else e.length?setTimeout(function(){for(var l=0;l<
e.length;l++){var k=e[l].tags;var r="";if(k){if((k=k.split(","))&&k.length)for(var w=0;w<k.length;w++){var t=k[w].split("=");t&&2==t.length&&("BANDWIDTH"==t[0].toString().trim()&&(r+=parseInt(parseInt(t[1])/1024)+" Kbps "),"RESOLUTION"==t[0].toString().trim()&&(r+=t[1]+" "))}r=r.trim()}a.g.o(N({tabId:b.tabId,frameId:b.frameId},{1:"GET",2:e[l]["2"],6:"hls",fEx:"ts",4:"TS File "+r}))}},3E3):0<d&&(c="",60<d&&(c+=parseInt(d/60)+" min "),c+=parseInt(d%60)&&parseInt(d%60)+" sec",p={6:"hls",fEx:"ts",4:"TS File "+
c,fDu:c},p=N(p,{1:b["1"],2:b["2"],tabId:b.tabId,frameId:b.frameId,fS:b["7"],fileName:b.fileName}),Y(b,p),"POST"==p["1"]&&T(b,p),setTimeout(function(){a.g.o(p)},3E3))}W.o=function(a){var b=this.g[[a.tabId,a.frameId]];if(!b&&(b=this.g[[a.tabId,0]],!b))return;var c=a["2"],e=0,d;var f=0;for(d=c.length;f<d;f++){var g=c.charCodeAt(f);e=(e<<5)-e+g;e|=0}a.id=e;b.postMessage([1,a,b["2"]])};W.C=function(a){delete this.j[a.requestId]};
function ia(a,b){if(!a)return null;var c=a.raw;if(c){a="";for(b=0;b<c.length;b++){var e=c[b].bytes;if(e){e=new Uint8Array(e);for(var d=e.length,f=0;f<d;f++)a+=String.fromCharCode(e[f])}}return a}c=a.formData;if(!c)return null;d=J(b);a=[];d&&(d=d.toLowerCase());if("application/x-www-form-urlencoded"==d){for(e in c)for(d=c[e],e=e.split(" ").map(encodeURIComponent).join("+"),b=0;b<d.length;b++)a.length&&a.push("&"),a.push(e,"=",d[b].split(" ").map(encodeURIComponent).join("+"));return a.join("")}if("multipart/form-data"==
d){(f=Z(b,"boundary"))||(f="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(e in c)for(d=c[e],b=0;b<d.length;b++)a.push("--",f,'\r\nContent-Disposition: form-data; name="',e,'"\r\n\r\n',d[b],"\r\n");a.push("--",f,"--\r\n");return a.join("")}return null}
W.P=function(a){if(!("video/webm"!=a["8"].toLowerCase()&&"audio/webm"!=a["8"].toLowerCase()||1>a["2"].indexOf("signature=")&&1>a["2"].indexOf("sig="))){var b=this.g[[a.tabId,a.frameId]];b||(b=this.g[[a.tabId,0]]);if(b){var c=a["2"].indexOf("?");if(-1!=c){var e=a["2"].substring(0,c);c=a["2"].substring(c+1);a={2:"",mme:a["8"].split("/").shift(),ig:0,du:0,mK:"",purl:b["2"]};e+="?";c=c.split("&");for(var d=0;d<c.length;d++)O(c[d],"dur=")&&(a.du=parseFloat(c[d].split("=").pop())),O(c[d],"itag=")&&(a.ig=
c[d].split("=").pop()),O(c[d],"ei=")&&(a.mK=c[d].split("=").pop()),O(c[d],"range=")||O(c[d],"rbuf=")||O(c[d],"rn=")||(e=e+c[d]+"&");a.du&&a.ig&&(e=e.substring(0,e.length-1),a["2"]=e,b.postMessage([9,a]))}}}};
W.R=function(a){var b,c=a.requestId,e=this;if(b=this.j[c]){var d=a.url,f=a.method.toUpperCase(),g=R(d);if(!g||"http"!=g&&"https"!=g||"GET"!=f&&"POST"!=f)delete this.j[c];else{b.s=a.responseHeaders;var n=M(b.s,"Content-Type"),u=J(n).toLowerCase(),z=M(b.s,"Content-Disposition");J(z);a=parseInt(a.statusLine.split(" ",2).pop())||0;b.ca=0<=ba.indexOf(a);if(!b.ca){if(200==a||206==a){a=M(b.s,"Content-Length");var D=M(b.s,"Content-Range"),A=null;D&&(D=C.exec(D))&&(a=D[1]);a&&(A=parseInt(a));if(0!==A){b["2"]=
d;b["8"]=n;b["7"]=A;b.protocol=g;b["1"]=f;g=new URL(d);f=g.hostname;g=g.pathname;(a=g.split("/").pop().trim())&&(a=a.split("?").shift().trim());b.F=a||"";b.u=L(b.F);b.D=Z(z,"filename")||Z(n,"name");b.M=b.D&&L(b.D)||"";n=u?I[u]:!1;b.L=(n?n.split("|").shift():"").toLowerCase();b.i=b.L||b.M||b.u||"";b.fileName=b.D||b.F||"";b.fileName&&(n=b.fileName.lastIndexOf("."),-1<n&&(b.fileName=b.fileName.substr(0,n).trim()));b.fileName&&b.i&&(b.fileName+="."+b.i);!u&&b.i&&(u=ea(b.i));if(!Q(b.F.toLowerCase(),".json")&&
!Q(b.L.toLowerCase(),"json")&&!Q(b.M.toLowerCase(),"json")&&b.i&&-1<ca.indexOf(b.i.toUpperCase())){if(b.isKeyDown){delete this.j[c];return}var h=e.g[[b.tabId,b.frameId]];d=e.g[[b.tabId,0]];d=N(new U,{2:b["2"],1:b["1"],4:d&&d["4"]||h&&h["4"],5:d&&d["2"]||h&&h["2"],7:b["7"],8:b["8"],pageUrl:h&&h["2"]||b["2"]});"POST"==d["1"]&&T(b,d);Y(b,d);e.h=d;chrome.cookies.getAll({url:d["2"]},e.J);delete this.j[c];return{redirectUrl:"javascript:"}}var p=null;"m3u8"==b.i.toLowerCase()||"m3u8"==b.u.toLowerCase()?
p=new X(this):(new RegExp(atob("Xmh0dHBzPzovL2FwaVwucGVyaXNjb3BlXC50di9hcGkvdjIvZ2V0QWNjZXNzUHVibGlj"))).test(d)?p=new X(this,"json"):"POST"==b["1"]||Q(f.toLowerCase(),atob("dmltZW8="))||Q(f.toLowerCase(),atob("eW91dHViZQ=="))||Q(f.toLowerCase(),"google")||"txt"!=b.i.toLowerCase()&&"js"!=b.i.toLowerCase()||"xmlhttprequest"!=b.type||b["7"]&&262144<b["7"]||(p=new X(this));if(p)S({2:b["2"],G:function(t){ha(p,N({},b),t)}},N({},b));else if(P(f,atob("Z29vZ2xldmlkZW8uY29t"))&&O(g,atob("L3ZpZGVvcGxheWJhY2s=")))this.P(b);
else if((new RegExp(atob("Xig/Olt3LV0rLikqPyg/OnlvdXR1YmUuY29tfGdvb2dsZXZpZGVvLmNvbXx5b3V0dWJlLmdvb2dsZWFwaXMuY29tfGRvY3MuZ29vZ2xlLmNvbSkk"),"i")).test(f)){if(P(g,"player")&&"POST"==b["1"]&&0!=b.frameId){T(b,b);var l=b.postData;var k=l.indexOf('"videoId"');if(0>k)return;l=l.substr(k+9);k=l.indexOf('"');if(0>k)return;var r=l.indexOf('"',k+1);if(r<k)return;S({2:atob("aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj0=")+l.substr(k+1,r-k-1),G:function(t){for(var E=["formats","adaptiveFormats"],v=0;v<E.length;v++)if(l=
t,k=l.indexOf(E[v]),!(0>k||-1<l.indexOf("signatureCipher"))){l=l.substr(k);k=l.indexOf("[");r=l.indexOf("]");if(0>k||0>r||r<=k)break;l=l.substr(k+1,r-k-1);(h=e.g[[b.tabId,b.frameId]])||(h=e.g[[b.tabId,0]]);h&&h.postMessage([7,l,1==v])}}},null)}}else if(f==atob("cGxheWVyLnZpbWVvLmNvbQ==")&&O(g,"/video/")&&"application/json"==u)S({2:b["2"],G:function(t){var E=null;try{E=JSON.parse(t)}catch(F){}if(E){var v=E.request.files.progressive;v&&setTimeout(function(){for(var F=0;F<v.length;F++)e.o({1:"GET",2:v[F].url,
6:"media",tabId:b.tabId,frameId:b.frameId,fEx:"mp4",4:"MP4 File "+v[F].quality})},3E3)}}},b);else if(!(!H.test(b.i)&&!H.test(b.u)||da.test(b.i)||b["7"]&&65536>b["7"]||"ASF"==b.i&&655360>=b["7"]||"DCLK-AdSvr"==M(b.s,"Server"))){var w={2:b["2"],6:"media",1:b["1"],tabId:b.tabId,frameId:b.frameId,fEx:H.test(b.i)?b.i:b.u,7:b["7"],8:b["8"],fS:b["7"],fileName:b.fileName};"POST"==w["1"]&&T(b,w);Y(b,w);setTimeout(function(){e.o(w)},2E3)}}}delete this.j[c]}}}};
function T(a,b){var c=M(a.l,"Content-Type"),e=M(a.l,"Content-Disposition");a=ia(a.ea,c);if(!a||1>a.length)a=null;b.postData=a;c&&(b["10"]=c.trim());e&&(b["11"]=e.trim())}function Y(a,b){if(a.l)for(var c=0;c<a.l.length;c++)O(a.l[c].name.toLowerCase(),"x-")&&(b[a.l[c].name]=a.l[c].value)}W.O=function(a){if(!(0>a.tabId||0>a.frameId)){var b=this.j[a.requestId];b&&(b.isKeyDown=B,b.l=a.requestHeaders)}};
W.N=function(a){if(!(0>a.tabId||0>a.frameId))if("ftp"==R(a.url)){if(K(a.url)&&!B){var b=new U,c=this.g[[a.tabId,0]];c&&c["2"]&&(b["5"]=c["2"],b.pageUrl=c["2"]);c&&c["4"]&&(b["4"]=c["4"]);b["2"]=a.url;this.I(b);return{redirectUrl:"javascript:"}}}else b=a.requestId,c=this.j[b]||{id:b,2:a.url,tabId:a.tabId,frameId:a.frameId},"POST"==a.method.toUpperCase()&&(c.ea=a.requestBody),c.isKeyDown=B,this.j[b]=c};
function Z(a,b){if(!a)return null;b=b.toLowerCase();a=a.split(";");a.shift();for(var c=0;c<a.length;c++){var e=a[c],d=e.indexOf("=");if(0<d){var f=e.substr(0,d).trim().toLowerCase(),g="*"==f[f.length-1];g&&(f=f.substr(0,f.length-1).trimRight());if(f==b)return a=e.substr(d+1).trim(),c=a.length-1,'"'==a[0]&&'"'==a[c]&&(a=a.substring(1,c)),g&&(a=a.split("'",3).pop()),unescape(a)}else if(0>d&&e.trim().toLowerCase()==b)return""}return null}W.m=function(a){a.addListener.apply(a,Array.prototype.slice.call(arguments).slice(1))};
W.U=function(a){var b=a.sender.tab;if(b&&0<=b.id){var c=a.sender.frameId,e=a.id||this.aa++,d=b.id;a.id=e;a["4"]=b.title;a.tabId=d;a.frameId=c;a.da=0==c;a["2"]=a.sender.url||a.da&&b.url||null;a.onMessage.addListener(this.W.bind(this,a));a.onDisconnect.addListener(this.V.bind(this,a));this.H[e]=a;this.g[[d,c]]=a;a.postMessage([3,a.id]);a.postMessage([13,!0]);a.sender=null}};
W.W=function(a,b){switch(b[0]){case 2:var c=b[2],e=b[3];(a=this.H[b[1]])&&c&&(a["2"]=c);a&&e&&(a["4"]=e);break;case 4:B=b[1];break;case 6:c=b[1];a=(a=a.tabId)&&this.g[[a,0]];var d=new U;d["1"]=c["1"]||"GET";d["2"]=c["2"];c["3"]&&(d["3"]=c["3"]);d.pageUrl=b[2];d["4"]=b[3]||a&&a["4"]||"";d["5"]=a&&a["2"]||d.pageUrl;d["9"]=b[4];c["7"]&&(d["7"]=c["7"]);c["8"]&&(d["8"]=c["8"]);d["6"]=c["6"]||"media";c.postData&&(d.postData=c.postData);c["10"]&&(d["10"]=c["10"]);c["11"]&&(d["11"]=c["11"]);for(e in c)O(e.toLowerCase(),
"x-")&&(d[e]=c[e]);this.h=d;chrome.cookies.getAll({url:d["2"]},this.J)}};W.V=function(a){for(var b in this.g)this.g[b]==a&&delete this.g[b];delete this.H[a.id]};W.ba=function(a){var b=[5],c=this.g;a=a.toString()+",";for(var e in c)O(e,a)&&c[e].postMessage(b)};W.fa=function(a){var b=this.g,c;for(c in b)b[c].postMessage(a)};new V;

