var y=chrome.extension.getURL("img/icon16.png"),B=chrome.extension.getURL("img/close16.png"),C={"-1":"none",1:""},D={242:"240p",243:"360p",244:"480p",246:"480p",247:"720p",248:"1080p",271:"1440p",272:"2160p",278:"144p",302:"720p",303:"1080p",308:"1440p",335:"1080p",336:"1440p",337:"2160p"},E=[171,172,249,250,251];function F(a){return document.getElementById(a)}window.el=F;
function J(){var a=document.location.host.toLowerCase(),b=atob("ZmFjZWJvb2suY29t"),c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function K(a){var b=new XMLHttpRequest;b.timeout=2E4;b.open("GET",a["2"],!0);b.onreadystatechange=function(){4==b.readyState&&(a.ra||function(){})(b.responseText)};b.send()}function L(a){var b=0,c;var d=0;for(c=a.length;d<c;d++){var e=a.charCodeAt(d);b=(b<<5)-b+e;b|=0}return b}
function M(a){return a.replace(/\\u([\d\w]{4})/gi,function(b,c){return String.fromCharCode(parseInt(c,16))})}function N(a){if(!a)return{left:0,top:0};try{var b=a.getBoundingClientRect();return b?{left:Math.round(b.left+window.pageXOffset),top:Math.round(b.top+window.pageYOffset)}:null}catch(c){return null}}
function O(a){if(a){var b;(b=a["4"])||(b=a.fS,b=(a.fEx.toUpperCase()||"MP4")+" File  "+((!b||0>b?" ":1E3>b?b+" Bytes":1E6>b?(b/1024).toFixed(1)+" KB":1E9>b?(b/1048576).toFixed(2)+" MB":(b/1073741824).toFixed(3)+" GB")||a.fDu));a=b}else a="";return a}function P(a,b,c){this.D=a;a.i[c]=this;this.S=c;this.J="neatTable"+c;this.N="neatHCell"+c;this.g=null;this.o=b;this.j=null;this.position={left:0,top:0};this.F=-1;this.items=[];this.R=this.P=0;this.u=this.C=!1}var Q=P.prototype;
Q.G=function(a){var b=Array.prototype.slice.call(arguments);b[2]=b[2].bind(this);a.addEventListener.apply(a,b.slice(1))};Q.A=function(){this.g&&(this.g.style.left=this.position.left+"px",this.g.style.top=this.position.top+"px",this.g.style.zIndex+=500)};Q.$=function(a){this.K(!0);this.D.ka(this.items[a])};Q.K=function(a){if(!a||-1!=this.F){var b=F(this.J).rows;this.F=a?-1:-this.F;for(a=1;a<b.length;a++)b[a].style.display=C[this.F]}};
Q.I=function(a){var b=this,c=this.D.M(this.items[a]);var d=F(this.J).insertRow(-1);d.cssText="all:revert;padding:0px;margin:0px;width:100%;line-height:100% !important;height:19px !important";d.style.display=C[b.F];var e=d.insertCell(0);e.style.cssText="all:revert;letter-spacing:normal;line-height:100% !important;width:100%;height:19px !important;margin:0px;padding:0px;padding-left:5px;vertical-align:middle;color:black !important;cursor:default;border:dotted 1px black;background:#c9dff2 !important;direction:ltr;text-align:left;font-family:tahoma !important;font-style:normal;font-weight:bold;font-size:7pt !important;";
c=O(c);0==a&&1==this.items.length?(e.innerHTML=("<table style='all:revert;border-spacing:0px;border-collapse:separate;padding:0px;margin:0px;width:100%;border:solid 1px black;direction:ltr;line-height:100% !important;);'><tr style='all:revert;padding:0px;margin:0px;line-height:100% !important;height:19px !important'><td style='all:revert;background:#c9dff2 !important;padding:0px;margin:0px;width:20px;height:19px !important;text-align:center;vertical-align:middle;line-height:100% !important;'><img onclick='alert(\"NeatDownloadManager Video/Audio Panel.\")'  src='"+
y+"'/></td><td id='HeaderCellID' style='all:revert;letter-spacing:normal;padding:0px;margin:0px;vertical-align:middle;color:black !important;cursor:default;background:#c9dff2 !important;direction:ltr;text-align:center;font-family:tahoma !important;font-style:normal;font-weight:bold;font-size:7pt !important;height:19px !important;line-height:100% !important;'></td><td style='all:revert;background:#c9dff2 !important;padding:0px;margin:0px;width:20px;height:19px !important;text-align:center;vertical-align:middle;line-height:100% !important;'><img id='CloseImgID' src='"+
B+"'/></td></tr></table>").replace("HeaderCellID",b.N).replace("CloseImgID","CloseImg"+b.S),e.style.paddingLeft="0px",d=F(b.N),d.innerText=" "+c,d.onmouseover=function(){this.style.color="red"},d.onmouseout=function(){this.style.color="black"},d.onclick=function(){0==b.u&&b.$(0);b.u=!1},F("CloseImg"+b.S).onclick=function(){b.g.style.display="none"}):(e.innerText=" "+(a+1).toString()+"- "+c,e.onmouseover=function(){this.style.background="white";this.style.color="red"},e.onmouseout=function(){this.style.background=
"#c9dff2";this.style.color="black"},d.onmousedown=function(){b.$(a)})};
Q.L=function(a){var b=this,c=this.D.M(a),d=null,e=this.o?"absolute":"fixed";this.o&&!this.C&&(d=N(this.o));d&&(this.position={left:Math.max(0,d.left-1),top:Math.max(0,d.top-19-4)});this.g?this.A():(this.g=document.createElement("DIV"),this.g.style.cssText="all:revert;padding:0px;margin:0px;position:"+e+";z-index:100000000;width:200px;left:"+this.position.left+"px;top:"+this.position.top+"px;direction:ltr;text-align:center;background:#c9dff2 !important;line-height:100% !important;",this.g.id="neatDiv"+
this.S,this.g.style.display=this.D.H?"":"none",document.body.appendChild(this.g),d=document.createElement("TABLE"),d.id=this.J,d.style.cssText="all:revert;border-spacing:0px;border-collapse:separate;padding:0px;margin:0px;line-height:100% !important;direction:ltr;width:100%;",this.g.appendChild(d),this.G(b.g,"mousemove",b.ta),this.G(b.g,"mousedown",b.sa),this.G(b.g,"mouseup",b.T),this.G(b.g,"mouseout",b.ua),this.G(b.g,"mouseover",b.va),this.j=setTimeout(function(){b.g.style.opacity=.4;b.j=null},1E4));
if(!(-1<this.items.indexOf(a)&&"hls"!=c["6"])){c=O(c);if(this.items.length&&(" MP4 File HQ"==c||" MP4 File LQ"==c))for(d=0;d<this.items.length;d++)if(c==O(this.D.M(this.items[d]))){this.items[d]=a;this.g.style.display=this.D.H?"":"none";this.A();return}this.items.push(a);a=this.items.length-1;c=F(b.J).rows;var f;a&&(f=F(b.N));0==a?this.I(0):1==a?(this.I(0),this.I(1),f.onclick=function(g){g.stopPropagation();g.preventDefault();0==b.u&&b.K();b.u=!1},f.innerText=" 2 Files"):(this.I(a),f.innerText=" "+
(a+1).toString()+" Files");c[0].style.display=""}};Q.sa=function(a){0==a.button&&(this.C=!0,this.u=!1,this.P=a.clientX,this.R=a.clientY,a.stopPropagation(),a.preventDefault())};Q.ta=function(a){if(this.C){this.K(!0);var b=a.clientX-this.P,c=a.clientY-this.R;!this.u&&(this.u=b||c);this.position.left+=b;this.position.top+=c;this.P=a.clientX;this.R=a.clientY;this.A()}else this.u=!1};
Q.ua=function(){this.C=!1;this.j&&(clearTimeout(this.j),this.j=null);var a=this;this.j=setTimeout(function(){a.g.style.opacity=.4;a.j=null},5E3)};Q.va=function(){this.C=!1;this.j&&(clearTimeout(this.j),this.j=null);this.g.style.opacity=1};Q.T=function(){this.C=!1};
if(!window.m){var R=function(a){a=N(a.o);return!a||0>a.left||0>a.top},S=function(a,b){return 15>Math.abs(a.left-b.left)&&15>Math.abs(a.top-b.top)},T=function(){this.ca=null;this.v={};this.i={};this.h=[];this.O=!1;this.ba=this.aa=-1;this.Counter=1;this.l=null;this.H=!0;this.X=[];this.port=chrome.runtime.connect({name:"neat"});this.ea=Math.ceil(2E6*Math.random());this.port.onMessage.addListener(this.pa.bind(this));this.port.onDisconnect.addListener(this.qa.bind(this));if(J()){var a=this;this.oa=new window.MutationObserver(function(b){b.forEach(function(c){a.la(c.target)})});
this.oa.observe(document,{childList:!0,subtree:!0})}this.m(window,"keydown",this.Y,!0);this.m(window,"keyup",this.Y,!0);this.m(window,"mouseup",this.T,!0);this.m(window,"resize",this.Aa);this.m(document,"DOMContentLoaded",this.za);this.m(document,"click",this.na)};window.m=!0;Q=T.prototype;Q.ma=function(a,b){b.hd&&this.B({id:L(b.hd),1:"GET",2:b.hd,fEx:"mp4",4:" MP4 File HQ"},window.location.href,a,!1);b.sd&&this.B({id:L(b.sd),1:"GET",2:b.sd,fEx:"mp4",4:" MP4 File LQ"},window.location.href,a,!1)};
Q.ia=function(a){for(;(a=a.parentElement)&&1>a.querySelectorAll("video").length;);if(a)return a.querySelectorAll("video")[0]};Q.ga=function(a,b){var c=this;K({2:"https://www.facebook.com/video/embed?video_id="+b,ra:function(d){var e=/"sd_src_no_ratelimit":"(.*?)"/.exec(d),f=/"hd_src_no_ratelimit":"(.*?)"/.exec(d);e&&e.length||(e=/"sd_src":"(.*?)"/.exec(d));f&&f.length||(f=/"hd_src":"(.*?)"/.exec(d));d={sd:e&&e.length?e[1].replace(/\\/g,""):"",hd:f&&f.length?f[1].replace(/\\/g,""):""};e=c.ia(a);void 0!==
e&&c.ma(e,d)}})};Q.la=function(a){var b=this;a=a.querySelectorAll('a[href*="/videos/"]');a.length&&Array.from(a,function(c){if(!c.getAttribute("NEAT_DM")){c.setAttribute("NEAT_DM",1);var d=c.href.match(/.*\/videos\/(\d+)\/.*/i);d&&b.ga(c,d[1])}})};Q.M=function(a){return this.v[a]};Q.ya=function(){this.port.postMessage([2,this.ca,window.location.href,this.getTitle()])};Q.za=function(a){for(var b=this,c=document.getElementsByTagName("SCRIPT"),d,e,f,g,h=!1,p=new RegExp(atob("InByb2dyZXNzaXZlIjpccypcWw==")),
q=0;q<c.length;q++){var l=c[q];d=l.innerText;if(a&&!h&&-1<d.indexOf("itag")&&0>d.indexOf("signatureCipher")){for(var n=["formats","adaptiveFormats"],r=0;r<n.length;r++)e=d,f=e.indexOf(n[r]),0>f||(e=e.substr(f),f=e.indexOf("["),g=e.indexOf("]"),0>f||0>g||g<=f||(e=e.substr(f+1,g-f-1),h=this.W(e,1==r)));if(this.Ba)break}if(0<=document.location.host.toLowerCase().indexOf("vimeo")&&!l.src&&p.test(l.innerText)&&(e=l.innerText,f=e.indexOf('"progressive"'),!(0>f||(g=e.indexOf("]",f),0>g)))){e=e.substr(f,
g-f+1);d=null;try{d=JSON.parse("{"+e+"}")}catch(u){}if(d){var t=d.progressive;t&&setTimeout(function(){for(var u=0;u<t.length;u++)b.B({id:L(t[u].url),1:"GET",2:t[u].url,fEx:"mp4",4:"MP4 File "+t[u].quality},window.location.href,null,!1)},2E3);break}}}};Q.W=function(a,b){var c=this,d={18:{e:"MP4",s:"360p"},22:{e:"MP4",s:"720p"},37:{e:"MP4",s:"1080p"},38:{e:"MP4",s:"1080p"},82:{e:"MP4",s:"360p"},84:{e:"MP4",s:"720p"},132:{e:"MP4",s:"240p"},151:{e:"MP4",s:"144p"}};a=M(a);a=a.replace(/\\/g,"");var e=
[],f="";a=a.split("}");if(1>a.length)return!1;for(var g=0;g<a.length;g++){var h=a[g].trim(),p={},q;if(h&&!(0>h.indexOf("itag"))){var l=h.indexOf('"url"');if(!(0>l)){l=h.indexOf('"',l+5);var n=h.indexOf('"',l+1);if(!(0>l||0>n||n<=l||(h=p.url=decodeURIComponent(h.substr(l+1,n-l-1)),l=h.indexOf("?"),0>l))){l=h.substring(l+1).split("&");for(n=0;n<l.length;n++)0==l[n].indexOf("itag=")&&(q=p.itag=parseInt(l[n].split("=").pop())),0==l[n].indexOf("dur=")&&(p.dur=parseFloat(l[n].split("=").pop())),0==l[n].indexOf("ei=")&&
(p.mK=l[n].split("=").pop());h&&q&&(0<h.indexOf("signature=")||0<h.indexOf("sig="))&&(!b||p.dur)&&(b||d[q])&&(!b||D[q]||-1<E.indexOf(q))&&(b?e.push({2:h,mme:0>E.indexOf(q)?"video":"audio",ig:q,du:p.dur,mK:p.mK,purl:window.location.href}):(h=parseInt(p.dur),f=p.timeStr=60>h?h+" sec":parseInt(h/60)+" min "+(parseInt(h%60)?parseInt(h%60)+" sec":""),e.push(p)))}}}}if(!e.length)return!1;b?setTimeout(function(){for(var r=e.length-1;0<=r;r--)c.Z(e[r])},2E3):(this.xa(),setTimeout(function(){for(var r=0;r<
e.length;r++){var t=e[r];c.B({id:L(t.url),ig:t.itag,1:"GET",2:t.url,fEx:d[t.itag].e,4:d[t.itag].e+" File "+d[t.itag].s+", "+(t.timeStr||f)},window.location.href,null,!1)}},2E3));return!0};Q.xa=function(){this.h=[];for(var a in this.i)for(var b=this.i[a],c=0;c<b.items.length;c++){var d=this.v[b.items[c]];if(d&&d.ig){this.U(a,!0);break}}};Q.U=function(a,b){var c=this.i[a];if(c){if(b)for(b=0;b<c.items.length;b++)delete this.v[c.items[b]];try{document.body.removeChild(c.g)}catch(d){}delete this.i[a]}};
Q.ka=function(a){(a=this.v[a])&&this.port.postMessage([6,a,window.location.href,this.getTitle(),O(a)])};Q.ha=function(a,b){var c=null,d=["VIDEO","AUDIO","OBJECT","EMBED"];try{var e=document.activeElement,f=0,g,h,p=e&&0<=d.indexOf(e.tagName)?e:null;p||(p=(e=document.elementFromPoint(this.aa,this.ba))&&0<=d.indexOf(e.tagName)?e:null);for(var q=0;q<d.length;q++){for(var l=document.getElementsByTagName(d[q]),n=0;n<l.length;n++)if(e=l[n],3!=q||atob("YXBwbGljYXRpb24veC1zaG9ja3dhdmUtZmxhc2g=")==e.type.toLowerCase()){var r=
e.src||e.data;if(r&&(r==a||r==b)){var t=e;break}if(p||u)var u=e;else{var z=e.clientWidth,A=e.clientHeight;if(z&&A){var G=window.getComputedStyle(e);if(!G||"hidden"!=G.visibility){var H=z*A;A<1.4*z&&z<3*A&&H>f&&(f=H,g=e);h||(h=e)}}}}if(t)break}(c=t||p||u||g||h)||(c=document.querySelectorAll("video,audio")[0]);if(!c)return null;if("EMBED"==c.tagName&&!c.clientWidth&&!c.clientHeight){var I=c.parentElement;"OBJECT"==I.tagName&&(c=I)}return c}catch(U){return null}};Q.ja=function(a){try{var b=parseInt(a.getAttribute("JM_NEAT"));
b||(b=this.ea<<10|this.Counter++,a.setAttribute("JM_NEAT",b));return b}catch(c){}};Q.getTitle=function(){var a="";try{a=document.title||document.getElementsByTagName("title")[0].innerText,a=a.trim()}catch(b){}return a?a=a.replace(/[ \t\r\n\u25B6]+/g," ").trim():""};Q.Y=function(a){8!=a.keyCode&&46!=a.keyCode||this.port.postMessage([4,"keydown"==a.type])};Q.T=function(a){0==a.button&&(this.aa=a.clientX,this.ba=a.clientY)};Q.Aa=function(){if(!this.O){this.O=!0;var a=this;window.setTimeout(function(){for(var b in a.i){var c=
a.i[b],d=null;c.o&&(d=N(c.o));if(d){try{document.body.removeChild(c.g)}catch(e){}c.position.left=Math.max(0,d.left-1);c.position.top=Math.max(0,d.top-19-4);document.body.appendChild(c.g)}c.A()}a.O=!1},500)}};Q.B=function(a,b,c,d){var e=this,f=-1,g=null,h;d=d&&(new RegExp(atob("LipmYWNlYm9vay5jb20kfC4qdmltZW8uY29tJHwuKnlvdXR1YmUuY29tJA=="),"i")).test(window.location.host)&&!(!a.fS||4194304<a.fS);a.id||(a.id=L(a["2"]));c||(c=this.ha(a["2"],b));if(!c)for(h in this.i){g=this.i[h];f=h;break}if(!c&&!g){if(d)return;
g=new P(e,null,0)}else if(!g)if(f=this.ja(c),g=this.i[f],!g){if(d)return;g=new P(e,c,f);b=N(c);c={left:Math.max(0,b.left-1),top:Math.max(0,b.top-19-4)};for(h in this.i)if(h&&h!=f&&(b=this.i[h],S(c,b.position))){for(c=0;c<b.items.length;c++)g.L(b.items[c]);this.U(h,!1);break}if(0!=f&&this.i[0]){b=this.i[0];for(c=0;c<b.items.length;c++)g.L(b.items[c]);this.U(0,!1)}}else{if(d){g.A();return}}else if(d){g.A();return}f=O(a);for(h=0;h<g.items.length;h++)if(b=O(e.v[g.items[h]]),0==f.trim().indexOf("TS File")&&
f==b)return;e.v[a.id]=a;g.L(a.id);g.o&&R(g)&&!this.l&&(e.l=setInterval(function(){e.fa(g)},1500))};Q.fa=function(a){if(a&&a.o){var b=N(a.o);b&&(a.position={left:Math.max(0,b.left-1),top:Math.max(0,b.top-19-4)},a.A());!b||0>b.left||0>b.top||(clearInterval(this.l),this.l=null)}else clearInterval(this.l),this.l=null};Q.V=function(a,b){var c=this,d=a.du,e="";e=60>d?parseInt(d)+" sec":parseInt(d/60)+" min "+(parseInt(d%60)?parseInt(d%60)+" sec":"");var f={id:L(a["2"]+b["2"]),2:a["2"],3:b["2"],ig:a.ig,
4:"MKV File "+D[a.ig]+", "+e};setTimeout(function(){c.B(f,a.purl,null,!1)},3E3)};Q.Z=function(a){if("video"!=a.mme||D[a.ig]){var b;for(b=0;b<this.h.length;b++)if(a.ig==this.h[b].ig&&a.mK==this.h[b].mK)return;a.used=!1;if("video"==a.mme){var c=null;for(b=0;b<this.h.length;b++)if("audio"==this.h[b].mme&&!this.h[b].used&&a.mK==this.h[b].mK){this.h[b].used=!0;c=this.h[b];break}if(!c)for(b=0;b<this.h.length;b++)if("audio"==this.h[b].mme&&a.mK==this.h[b].mK){this.h[b].used=!0;c=this.h[b];break}c&&(a.used=
!0,this.V(a,c))}else{c=null;for(b=0;b<this.h.length;b++)if("video"==this.h[b].mme&&0==this.h[b].used&&a.mK==this.h[b].mK){this.h[b].used=!0;c=this.h[b];break}c&&(a.used=!0,this.V(c,a))}this.h.push(a)}};Q.pa=function(a){var b=this;switch(a[0]){case 1:b.B(a[1],a[2],null,!0);break;case 3:var c=a[1];c&&(b.ca=c);b.ya();break;case 5:b.da();break;case 7:b.W(a[1],a[2]);break;case 9:setTimeout(function(){b.Z(a[1])},2E3);break;case 13:c=a[1],c!=b.H&&(b.H=c,b.da())}};Q.m=function(a){var b=Array.prototype.slice.call(arguments);
b[2]=b[2].bind(this);this.X.push(b);a.addEventListener.apply(a,b.slice(1))};Q.na=function(){for(var a in this.i)this.i[a].K(!0)};Q.wa=function(){try{for(var a in this.i)document.body.removeChild(this.i[a].g)}catch(b){}this.i={};this.v={};this.h=[];this.l&&clearInterval(this.l);this.l=null};Q.da=function(){var a=this.H?"":"none";try{for(var b in this.i)this.i[b].g.style.display=a}catch(c){}};Q.qa=function(){for(var a;a=this.X.shift();){var b=a.shift();b.removeEventListener.apply(b,a)}this.wa();this.port=
null;window.m=!1};new T};

